[build]
  # Команда для сборки вашего React приложения
  command = "npm run build"
  # Папка, где размещаются статические файлы после сборки
  publish = "dist"

[[redirects]]
  # Обработка маршрутизации для вашего SPA
  from = "/*"
  to = "/index.html"
  status = 200
